CCPP=g++

all: release

release: 
	${CCPP} -std=c++17 ./main.cpp ./geneticAlgorithm.cpp ./hillClimbingCandidate.cpp ./tsp.cpp ./tspMap.cpp ./helper.cpp ./simulatedAnnealing.cpp -o app.exe

run:
	./app.exe
